project:
  type: book
  output-dir: docs

book:
  title: "NVivo Course"
  author: "Data Analytics Service"
  date: last-modified
  chapters:
    - index.qmd
    - course_overview.qmd
    - installation.qmd
   
    - part: "PART 1 NVivo Basics"
      chapters:
        - part1/opening.qmd
        - part1/environment.qmd
        - part1/project.qmd
        - part1/creating_documents.qmd
        - part1/importing_transcripts.qmd
    - part: "PART 8 Notes: Memos and Annotations"
      chapters:
        - part8/creating_notes.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

